### ISSUE TITLE
Settings aren't loading 

### ISSUE THREAD

**Issue by iamthelonely** [Txreq/asidar#1]
All of my preferences are either blank or "undefined" in the very first launch of the application, the audio quality is saying `undefined` and the default download path is just blank.

**Comment by Txreq** [comment]
Thank you for reporting the issue, I opened the project, and I found where the issue is coming from, it's due to the `electron-builder` the packager I'm using.
When the app is installed and gets opened by the system, it won't load the settings and I didn't manage to know why yet, a temporary fix I have set the packager to not open the app after finishing the installation.

However, I guess everything is working now!
Please check the latest release: [v0.7.3](https://github.com/Txreq/asidar/releases/tag/v0.7.3)
